--31. Revising Aggregations - The Count Function
SELECT COUNT(*)
FROM CITY
WHERE POPULATION > 100000

--32. Revising Aggregations - The Sum Function
SELECT SUM(POPULATION)
FROM CITY
WHERE DISTRICT = 'California'

--33. Revising Aggregations - Averages
SELECT AVG(POPULATION)
FROM CITY
WHERE DISTRICT = 'California'

--34. Average Population
SELECT FLOOR(AVG(POPULATION))
FROM CITY

--35. Japan Population
SELECT SUM(POPULATION)
FROM CITY
WHERE COUNTRYCODE = 'JPN'

--36. Population Density Difference
SELECT MAX(POPULATION) - MIN(POPULATION)
FROM CITY

--37. The Blunder
SELECT CEIL(AVG(SALARY)-AVG(REPLACE(SALARY,'0',''))) 
FROM EMPLOYEES

--38. Top Earners
SELECT (SALARY * MONTHS) AS EARNINGS, COUNT(*)
FROM EMPLOYEE
GROUP BY 1
ORDER BY EARNINGS DESC
LIMIT 1

